#!/usr/bin/env python3
"""Translate Ruth chapter 1 from English to Nama using the fine-tuned model."""

import warnings
warnings.filterwarnings("ignore")

import logging
logging.getLogger("transformers.modeling_utils").setLevel(logging.ERROR)
logging.getLogger("accelerate.utils.modeling").setLevel(logging.ERROR)

import os
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "1"

import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from parse_usfm import parse_usfm

CHECKPOINT = "./output/nllb-nama-pilot/checkpoint-1080"
NEW_LANG_CODE = "nmx_Latn"
MAX_LENGTH = 128
REPETITION_PENALTY = 1.3


def main():
    # Load model
    print(f"Loading checkpoint: {CHECKPOINT}")
    tokenizer = AutoTokenizer.from_pretrained(CHECKPOINT)
    model = AutoModelForSeq2SeqLM.from_pretrained(CHECKPOINT, tie_word_embeddings=False)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    model.eval()
    print(f"Model on {device}")

    # Parse Ruth
    ruth = parse_usfm("raw/eng_full_usfm/09-RUTengwebp.usfm")
    chapter = ruth["RUT"][1]

    # Translate
    tokenizer.src_lang = "eng_Latn"
    forced_bos = tokenizer.convert_tokens_to_ids(NEW_LANG_CODE)

    print("\n" + "=" * 60)
    print("  RUTH CHAPTER 1 — English → Nama (draft)")
    print("=" * 60)

    translations = []
    for verse_num in sorted(chapter.keys()):
        eng_text = chapter[verse_num]
        inputs = tokenizer(
            eng_text, return_tensors="pt", max_length=MAX_LENGTH, truncation=True
        ).to(device)
        with torch.no_grad():
            generated = model.generate(
                **inputs,
                forced_bos_token_id=forced_bos,
                max_new_tokens=MAX_LENGTH,
                repetition_penalty=REPETITION_PENALTY,
            )
        pred = tokenizer.decode(generated[0], skip_special_tokens=True)
        translations.append((verse_num, eng_text, pred))

        print(f"\n[RUT 1:{verse_num}]")
        print(f"  ENG:  {eng_text}")
        print(f"  NMX:  {pred}")

    # Save to file
    out_path = "ruth_1_draft.txt"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("RUTH CHAPTER 1 — Nama Draft Translation\n")
        f.write("=" * 50 + "\n")
        f.write("Generated by NLLB-200 fine-tuned on Nama Luke+Acts\n")
        f.write("This is a machine-generated DRAFT for review.\n")
        f.write("=" * 50 + "\n\n")
        for verse_num, eng, nama in translations:
            f.write(f"[RUT 1:{verse_num}]\n")
            f.write(f"  ENG: {eng}\n")
            f.write(f"  NMX: {nama}\n\n")
    print(f"\nSaved to {out_path}")


if __name__ == "__main__":
    main()
